name: get-publish-profile

on:
  [workflow_dispatch]

permissions:
  id-token: write
  contents: read

env:
  AZURE_RESOURCEGROUP_NAME: apim-test
  PUBLISH_PROFILE: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - uses: azure/CLI@v1
      with:
        azcliversion: 2.40.0
        inlinescript: |
          ${{env.PUBLISH_PROFILE}}= az functionapp deployment list-publishing-profiles --name function-with-swagger20221101164153 --resource-group apim-test
          echo ${{env.PUBLISH_PROFILE}}