name: get-publish-profile

on:
  [workflow_dispatch]

permissions:
  id-token: write
  contents: read

env:
  AZURE_RESOURCEGROUP_NAME: apim-test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    # - uses: azure/CLI@v1
    #   with:
    #     azcliversion: 2.40.0
    #     inlinescript: |
    #       echo 'PUBLISH_PROFILE' >> $env:GITHUB_ENV
    #       az functionapp deployment list-publishing-profiles --name function-with-swagger20221101164153 --resource-group apim-test >> $env:GITHUB_ENV
    #       echo ${{env.PUBLISH_PROFILE}}
    
    - name: variables
      run: |
          echo 'PUBLISH_PROFILE<<EOF' >> $GITHUB_ENV
          curl https://example.com >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

    - name: print
      run: echo "${{ env.PUBLISH_PROFILE }}"