name: add-api

on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read

env:
  AZURE_RESOURCEGROUP_NAME: apim-test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - uses: azure/CLI@v1
      with:
        azcliversion: 2.40.0
        inlinescript: |
          az apim api import -g apim-test --service-name jake-test-apim --path test-api --api-id e842634cc9c7475cbb9f6eecc6a481b2 --specification-url https://jdvstorage.blob.core.windows.net/sample/sample-api.json?sp=r&st=2022-11-01T21:08:58Z&se=2022-11-02T05:08:58Z&spr=https&sv=2021-06-08&sr=b&sig=cxqgwDkx631e1o4BhwN%2F3KEgmHK8dgY99D%2FnafzJXW4%3D --specification-format OpenApiJson