name: 'Delete function'

on:
  workflow_dispatch:
    inputs:
      functionName:
        description: 'name of function'
        default: 'functionName'
        required: true
        type: string

      env:
        description: 'Target environment'
        default: 'sandbox'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  check-and-delete:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2
      
      - name: 'Az Login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: 'Generate RG_NAME'
        run: |
          echo 'RG_NAME<<RG' >> $GITHUB_ENV
          echo 'rg-'${{ inputs.functionName }}'-cus' | sed s/[.]//g >> $GITHUB_ENV
          echo 'RG' >> $GITHUB_ENV

      - name: 'Set RG flag'
        run: |
          echo 'RG_FLAG<<RGF' >> $GITHUB_ENV
          az group exists -n ${{ env.RG_NAME }} >> $GITHUB_ENV
          echo 'RGF' >> $GITHUB_ENV
      
      - name: 'Check for Resource Group'
        run: |
          echo ${{env.RG_NAME}}
          echo ${{env.RG_FLAG}}