name: FunctionInfra-V3
## add CLI alternatives
on:
  workflow_dispatch:
    inputs:
      functionName:
        description: 'name of function'
        default: 'function name'
        required: true
        type: string

      env:
        description: 'Target environment'
        default: 'sandbox'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

env:
  FUNCTIONAPP_NAME: func-${{ inputs.functionName }}
  FUNCTIONAPP_PATH: './apis' ##Change this to ./${{inputs.functionName}}
  DOTNET_VERSION: '6.0.x'
  RG_NAME: rg-${{ inputs.functionName }}-cus

jobs:
  env-deploy:
    runs-on: ubuntu-latest ## SNGitHubRunner-Linux
    outputs:
      publish-profile: ${{ steps.publish-profile.outputs.PUBLISH_PROFILE }}
    steps:
      - name: 'Checkout GitHub'
        uses: actions/checkout@v3

      - name: 'Az Login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: 'Deploy Infra'
        uses: azure/arm-deploy@v1
        with:
          deploymentName: ${{ github.run_number }}
          scope: subscription
          region: westus
          template: ./deploy/function-app-infra.bicep
          parameters: functionName=${{inputs.functionName}} env=${{inputs.env}}

      - name: publish-profile
        id: publish-profile
        run: |
          echo 'PUBLISH_PROFILE<<EOF' >> $GITHUB_OUTPUT
          az functionapp deployment list-publishing-profiles --name ${{ env.FUNCTIONAPP_NAME }} --resource-group ${{ env.RG_NAME }} --xml >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

  app-build-and-deploy:
    needs: env-deploy
    runs-on: windows-latest ## SNGitHubRunner
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh
      run: |
        pushd './${{ env.FUNCTIONAPP_PATH }}'
        dotnet build --configuration Release --output ./output
        popd


    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.FUNCTIONAPP_NAME }}
        package: './packages/${{ inputs.functionName }}/output'
        publish-profile: ${{ needs.env-deploy.outputs.publish-profile }}

  update-apim:
    runs-on: ubuntu-latest ## SNGitHubRunner-Linux
    needs: app-build-and-deploy
    steps:
      - name: 'Az Login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: 'Update APIM'
        uses: azure/CLI@v1
        with:
          azcliversion: 2.40.0
          ## Chage -g ${{ env.RG_NAME }}
          inlinescript: |
            az apim api import -g apim-test --service-name jake-test-apim --path ${{inputs.functionName}} --display-name ${{inputs.functionName}} \
            --specification-url "https://${{env.FUNCTIONAPP_NAME}}.azurewebsites.net/api/swagger.json" --specification-format OpenApiJson