name: Deploy Function App 2

on:
  push:
    branches:
      - "main"
    paths:
      - "apis/*"
  

env:
  AZURE_FUNCTIONAPP_NAME: 'function-with-swagger20221101164153'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './apis'
  DOTNET_VERSION: '6.0.x'
  AZURE_RESOURCEGROUP_NAME: apim-test

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

  deploy-apim:
    needs: [build-and-deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: azure/CLI@v1
        with:
          azcliversion: 2.40.0
          inlinescript: |
            az apim api import -g ${{ env.AZURE_RESOURCEGROUP_NAME }} --service-name jake-test-apim --path test-api --api-id e842634cc9c7475cbb9f6eecc6a481b2 \
            --specification-url "https://function-with-swagger20221101164153.azurewebsites.net/api/swagger.json" --specification-format OpenApiJson
          