name: test
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Target environment'
        default: 'sandbox'
        required: true
        type: string

      function-name:
        description: 'name of the function'
        default: 'functiona'
        required: true
        type: string

jobs:

  calculate-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Calculate variables
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const { env } = ${{ inputs.env }}
            const { function_name } = ${{ inputs.function-name }}
            if (env === 'sandbox'){
              console.log('going to the sandbox')
            }
            else {
              console.log('not going to sandbox')
            }


  print-variables:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.username }}