name: test
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Target environment'
        default: 'sandbox'
        required: true
        type: string

      function-name:
        description: 'name of the function'
        default: 'functiona'
        required: true
        type: string

jobs:

  calculate-variables:
    runs-on: ubuntu-latest
    steps:
      - name: variables
        run: |
          resourceGroup = "${{ inputs.env }}"
          echo $resourceGroup